# Generated by Django 5.2.12 on 2026-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_knowledgebase_and_base_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestudyjob",
            name="attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="prestudyjob",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="prestudyjob",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prestudyjob",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prestudyjob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prestudyjob",
            name="task_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="prestudyjob",
            name="model_trace",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="prestudyjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("completed_with_fallback", "Completed With Fallback"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
