# Generated by Django 5.2.12 on 2026-03-20 05:55

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_prestudyjob_attempts_prestudyjob_error_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgechunk",
            name="embedding_vector",
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
    ]
