import json
import logging
from pathlib import Path
from typing import Any, Dict, List

from django import template
from django.conf import settings


logger = logging.getLogger(__name__)
register = template.Library()

_MANIFEST_CACHE: Dict[str, Any] = {"mtime": None, "data": {}, "path": None}


def _manifest_path() -> Path:
    """Return the manifest path generated by Vite."""
    dist_path = getattr(settings, "VITE_DIST_PATH", None)
    base_dir = Path(getattr(settings, "BASE_DIR", Path(__file__).resolve().parents[3]))
    root = Path(dist_path) if isinstance(dist_path, (str, Path)) else base_dir / "webapp" / "dist"
    candidates = [
        root / "manifest.json",
        root / ".vite" / "manifest.json",
    ]
    for candidate in candidates:
        if candidate.exists():
            _MANIFEST_CACHE["path"] = candidate
            return candidate
    # remember last tried path even if missing so we can log later
    _MANIFEST_CACHE["path"] = candidates[0]
    return candidates[0]


def _load_manifest() -> Dict[str, Any]:
    """Load (and cache) the Vite manifest data."""
    manifest_file = _manifest_path()
    try:
        stat = manifest_file.stat()
    except FileNotFoundError:
        _MANIFEST_CACHE.update({"mtime": None, "data": {}})
        return {}

    cached_mtime = _MANIFEST_CACHE.get("mtime")
    if cached_mtime == stat.st_mtime:
        return _MANIFEST_CACHE["data"]

    try:
        content = manifest_file.read_text(encoding="utf-8")
        manifest = json.loads(content)
    except json.JSONDecodeError:
        logger.warning("Failed to parse Vite manifest at %s", manifest_file)
        manifest = {}
    _MANIFEST_CACHE.update({"mtime": stat.st_mtime, "data": manifest})
    return manifest


def _static_url(path_fragment: str) -> str:
    """Prefix files with STATIC_URL to keep Django static handling."""
    base = (getattr(settings, "STATIC_URL", "/static/") or "/static/").rstrip("/")
    fragment = path_fragment.lstrip("/")
    return f"{base}/{fragment}"


def _get_entry(entry: str) -> Dict[str, Any]:
    manifest = _load_manifest()
    return manifest.get(entry, {})


@register.simple_tag
def vite_asset(entry: str = "src/main.ts") -> str:
    """Return the built JS asset path for the given entry."""
    chunk = _get_entry(entry)
    file_path = chunk.get("file")
    if not file_path:
        return ""
    return _static_url(file_path)


@register.simple_tag
def vite_css(entry: str = "src/main.ts") -> List[str]:
    """Return CSS assets emitted for the entry."""
    chunk = _get_entry(entry)
    css_files = chunk.get("css") or []
    return [_static_url(path) for path in css_files if path]
